### ISSUE TITLE
Crear la estructura de un articulo 

### ISSUE THREAD

**Issue by kr1lo** [KriLoMon/Farmacia#3]
Estructura articulo, debe contener los siguientes datos: 
- clave 
- nombreProducto
- presentacion
- precioVenta
- precioDescuento
- existencia
- **Fabricante**

**Comment by kr1lo** [comment]
Podrias tomar como referencia este ejemplo:

> struct **_stDireccion_** { 
>    char Calle[64]; 
>    int Portal; 
>    int Piso; 
>    char Puerta[3]; 
>    char CodigoPostal[6]; 
>    char Poblacion[32]; 
> };
>  
> struct stPersona { 
>    struct stNombre { 
>       char Nombre[32]; 
>       char Apellidos[64]; 
>    } NombreCompleto; 
>    **_stDireccion_ Direccion**; 
>    char Telefono[10]; 
> };

**Comment by AnabelBerumen** [comment]
`//FranciscoRosas
//AnabelChavez
//LuisZepeta
#include "stdio.h"
#include "conio.h"
#include "stdlib.h"
#include "string.h"
#include "ctype.h"
#define max 200
struct fabricante{
       char nombrelaboratorio[50];
       char calle[30];
       char colonia[50];
       char ciudad [20];
       int telefono;
       char email[50];
       };
struct articulo{
       int clave;
       char nombreproducto[30];
       char presentacion [30];
       float precioventa;
       float preciodescuento;
       int existencia;
       struct fabricante laboratorio;
       };
void leerdatos(int n, struct articulo art[]);
void ordenar (int n, struct articulo art[]);
void consultalista(int n, struct articulo art[]);
void busqueda (int n, struct articulo art[]);
void modificarregistro (int n, struct articulo art[]);
void grabararchivo (int n ,struct articulo art[]);
void leerarchivo (struct articulo art[]);

main(){
       struct articulo art[max];
       int n=0;
       char op;
       do{
            puts("A. Leer datos");
            puts("B. Ordenar por clave");
            puts("C. Consulta la lista");
            puts("D. Buscar un elemento de la lista");
            puts("E. Modificar un registro");
            puts("F. Grabar en un archivo");
            puts("G. Leer de un archivo");
            puts("H. Salir");
            printf("Selecciona una Opcion; ");
            op=toupper(getche());
            fflush(stdin);
            switch(op){
                 case('A'):printf("¿Cuantos articulos va a registrar?");
                           scanf("%d",&n);
                           leerdatos(n,art);
                           break;
                 case('B'):ordenar(n,art);
                           break;
                 case('C'):consultalista(n,art);
                           break;
                 case('D'):busqueda(n,art);
                           break;
                 case('E'):modificarregistro(n,art);
                           break;
                 case('F'):grabararchivo(n,art);
                           break;
                 case('G'):leerarchivo(art);
                 }
                 }
       while(op!='H');
            
       
}

void leerdatos(int n, struct articulo art[]){
     int i;
     system("cls");
     puts("Leer Datos");
     for(i=0;i<n;i++){
          printf("Clave del producto");
          scanf("%d",&art[i].clave);
          printf("Nombre del producto");
          gets(art[i].nombreproducto);
          printf("presentacion");
          gets(art[i].presentacion);
          printf("Precio de venta");
          scanf("%f",&art[i].precioventa);
          printf("Existencia");
          scanf("%d",&art[i].existencia);
          printf("Nombre del laboratorio");
          gets(art[i].laboratorio.nombrelaboratorio);
          printf("Calle");
          gets(art[i].laboratorio.calle);
          printf("Colonia");
          gets(art[i].laboratorio.colonia);
          printf("Ciudad");
          gets(art[i].laboratorio.ciudad);
          printf("Numero Telefonico");
          scanf("%d",&art[i].laboratorio.telefono);
          printf("Correo Electronico");
          gets(art[i].laboratorio.email);
     }
}

void ordenar (int n, struct articulo art[]){
     int i,j;
     struct articulo aux;
     for(i=0;i<n-1;i++){
          for(j=0;j<n-1;j++){
               if(art[j].clave>art[j+1].clave){
                    aux=art[j];
                    art[j]=art[j+1];
                    art[j+1]=aux;
               }
          }
     }
}

void cosultalista(int n, struct articulo art[]){
     int i;
     system("cls");
     puts("Consulta lista");
     for(i=0;i<n;i++){
          printf("Clave del producto: %d",art[i].clave);
          printf("Nombre del producto:");
          puts(art[i].nombreproducto);
          printf("Presentacion:");
          puts(art[i].presentacion);
          printf("Precio del articulo: $%10.2f",art[i].precioventa);
          (art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15);
          printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
          printf("Existencia del articulo: %d",art[i].existencia);
          printf("Nombre del laboratorio");
          puts(art[i].laboratorio.nombrelaboratorio);
          printf("Nombre de la calle");
          puts(art[i].laboratorio.calle);
          printf("Colonia");
          puts(art[i].laboratorio.colonia);
          printf("Cuidad");
          puts(art[i].laboratorio.ciudad);
          printf("Numero telefonico: %d",art[i].laboratorio.telefono);
          printf("Correo electronico");
          puts(art[i].laboratorio.email);
     }
}

void busqueda (int n, struct articulo art[]){
     int i;
     int posicion=-1;
     int b;
     system("cls");
     puts("Busqueda individual");
     printf("Clave del articulo a buscar");
     scanf("%d",&b);
     for(i=0;i<n;i++){
          if(b==art[i].clave){
               printf("Clave del producto: %d",art[i].clave);
               printf("Nombre del producto:");
               puts(art[i].nombreproducto);
               printf("Presentacion:");
               puts(art[i].presentacion);
               printf("Precio del articulo: $%10.2f",art[i].precioventa);
               art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15;
               printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
               printf("Existencia del articulo: %d",art[i].existencia);
               printf("Nombre del laboratorio");
               puts(art[i].laboratorio.nombrelaboratorio);
               printf("Nombre de la calle");
               puts(art[i].laboratorio.calle);
               printf("Colonia");
               puts(art[i].laboratorio.colonia);
               printf("Cuidad");
               puts(art[i].laboratorio.ciudad);
               printf("Numero telefonico: %d",art[i].laboratorio.telefono);
               printf("Correo electronico");
               puts(art[i].laboratorio.email);
          }
          else
               puts("Articulo no encontrado");
     }
}               
     
void modificarregistro (int n, struct articulo art[]){
     int i,op,b;
     printf("clave del producto que desea modificar");
     scanf("%d",&b);
     for(i=0;i<n;i++){
          if(b==art[i].clave){
               printf("Clave del producto: %d",art[i].clave);
               printf("Nombre del producto:");
               puts(art[i].nombreproducto);
               printf("Presentacion:");
               puts(art[i].presentacion);
               printf("Precio del articulo: $%10.2f",art[i].precioventa);
               art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15;
               printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
               printf("Existencia del articulo: %d",art[i].existencia);
               printf("Nombre del laboratorio");
               puts(art[i].laboratorio.nombrelaboratorio);
               printf("Nombre de la calle");
               puts(art[i].laboratorio.calle);
               printf("Colonia");
               puts(art[i].laboratorio.colonia);
               printf("Cuidad");
               puts(art[i].laboratorio.ciudad);
               printf("Numero telefonico: %d",art[i].laboratorio.telefono);
               printf("Correo electronico");
               puts(art[i].laboratorio.email);
               do{
                    printf("¿Que desea modificar?");
                    printf("1.Clave del producto");
                    printf("2.Nombre del producto");
                    printf("3.Presentacion");
                    printf("4.Precio del articulo");
                    printf("5.Existencia del articulo");
                    printf("6.Nombre del laboratorio");
                    printf("7.Calle");
                    printf("8.Colonia");
                    printf("9.Cuidad");
                    printf("10.Numero telefonico");
                    printf("11.Correo electronico");
                    printf("12.Modificar todo");
                    printf("13.Salir");
                    scanf("%d",&op);
                    switch(op){
                         case(1):printf("Nueva clave");
                                 scanf("%d",&art[i].clave);
                                 break;
                         case(2):printf("Nuevo nombre del producto");
                                 gets(art[i].nombreproducto);
                                 break;
                         case(3):printf("Nueva presentacion");
                                 gets(art[i].presentacion);
                                 break;
                         case(4):printf("Nuevo precio de venta");
                                 scanf("%f",&art[i].precioventa);
                                 break;
                         case(5):printf("existencia");
                                 scanf("%d",&art[i].existencia);
                                 break;
                         case(6):printf("Nombre del laboratorio");
                                 gets(art[i].laboratorio.nombrelaboratorio);
                                 break;
                         case(7):("Calle");
                                 gets(art[i].laboratorio.calle);
                                 break;
                         case(8):printf("Colonia");
                                 gets(art[i].laboratorio.colonia);
                                 break;
                         case(9):printf("cuidad");
                                 gets(art[i].laboratorio.ciudad);
                                 break;
                         case(10):printf("Numero telefonico");
                                  scanf("%d",&art[i].laboratorio.telefono);
                                  break;
                         case(11):printf("Correo electronico");
                                  gets(art[i].laboratorio.email);
                                  break;
                         case(12):printf("Clave del producto");
                                  scanf("%d",&art[i].clave);
                                  printf("Nombre del producto");
                                  gets(art[i].nombreproducto);
                                  printf("presentacion");
                                  gets(art[i].presentacion);
                                  printf("Precio de venta");
                                  scanf("%f",&art[i].precioventa);
                                  printf("Existencia");
                                  scanf("%d",&art[i].existencia);
                                  printf("Nombre del laboratorio");
                                  gets(art[i].laboratorio.nombrelaboratorio);
                                  printf("Calle");
                                  gets(art[i].laboratorio.calle);
                                  printf("Colonia");
                                  gets(art[i].laboratorio.colonia);
                                  printf("Ciudad");
                                  gets(art[i].laboratorio.ciudad);
                                  printf("Numero Telefonico");
                                  scanf("%d",&art[i].laboratorio.telefono);
                                  printf("Correo Electronico");
                                  gets(art[i].laboratorio.email);
               }
               while(op>=12);
               }
               else
               printf("Articulo no encontrado");
               }
          
     
}   
}
void grabararchivo (int n ,struct articulo art[]){
     file *pa;
     char nombrearch[]="Farmacia.dat";
     int i;
     system("cls");
     if((pa=fopen(nombrearch,"wb"))==NULL){
          printf("No se pudo abrir el archivo");}
     for(i=0;i<n;i++){
          fwrite((art[],sizeof art[i],1,pa);
          }
     fclose(pa);
     printf("\n\n Archivo grabado con exito...");
     system("pause");
}

void leerarchivo (struct articulo art[]){
     file*pa;
     char nombrearch[]="Farmacia.dat";
     int i;
     system ("cls");
     if((pa=fopen(nombrearch"rb"))==NULL){
     	printf ("no se pudo abrir el archivo");}
     	i=0;
     	while (!feof(pa)){
     		fread(&art[i],zizeof art[i],1,pa );
     		i++;
     	}
     	fclose (pa);
     	printf("n\n\ archivo leido con exito ...");
     	system ("pause");
     	return 0 i-1;
     }


`

**Comment by AnabelBerumen** [comment]
//FranciscoRosas
//AnabelChavez
//LuisZepeta
#include "stdio.h"
#include "conio.h"
#include "stdlib.h"
#include "string.h"
#include "ctype.h"
#define max 200
struct fabricante{
       char nombrelaboratorio[50];
       char calle[30];
       char colonia[50];
       char ciudad [20];
       int telefono;
       char email[50];
       };
struct articulo{
       int clave;
       char nombreproducto[30];
       char presentacion [30];
       float precioventa;
       float preciodescuento;
       int existencia;
       struct fabricante laboratorio;
       };
void leerdatos(int n, struct articulo art[]);
void ordenar (int n, struct articulo art[]);
void consultalista(int n, struct articulo art[]);
void busqueda (int n, struct articulo art[]);
void modificarregistro (int n, struct articulo art[]);
void grabararchivo (int n ,struct articulo art[]);
void leerarchivo (struct articulo art[]);

main(){
       struct articulo art[max];
       int n=0;
       char op;
       do{
            puts("A. Leer datos");
            puts("B. Ordenar por clave");
            puts("C. Consulta la lista");
            puts("D. Buscar un elemento de la lista");
            puts("E. Modificar un registro");
            puts("F. Grabar en un archivo");
            puts("G. Leer de un archivo");
            puts("H. Salir");
            printf("Selecciona una Opcion; ");
            op=toupper(getche());
            fflush(stdin);
            switch(op){
                 case('A'):printf("¿Cuantos articulos va a registrar?");
                           scanf("%d",&n);
                           leerdatos(n,art);
                           break;
                 case('B'):ordenar(n,art);
                           break;
                 case('C'):consultalista(n,art);
                           break;
                 case('D'):busqueda(n,art);
                           break;
                 case('E'):modificarregistro(n,art);
                           break;
                 case('F'):grabararchivo(n,art);
                           break;
                 case('G'):leerarchivo(art);
                 }
                 }
       while(op!='H');
            
       
}

void leerdatos(int n, struct articulo art[]){
     int i;
     system("cls");
     puts("Leer Datos");
     for(i=0;i<n;i++){
          printf("Clave del producto");
          scanf("%d",&art[i].clave);
          printf("Nombre del producto");
          gets(art[i].nombreproducto);
          printf("presentacion");
          gets(art[i].presentacion);
          printf("Precio de venta");
          scanf("%f",&art[i].precioventa);
          printf("Existencia");
          scanf("%d",&art[i].existencia);
          printf("Nombre del laboratorio");
          gets(art[i].laboratorio.nombrelaboratorio);
          printf("Calle");
          gets(art[i].laboratorio.calle);
          printf("Colonia");
          gets(art[i].laboratorio.colonia);
          printf("Ciudad");
          gets(art[i].laboratorio.ciudad);
          printf("Numero Telefonico");
          scanf("%d",&art[i].laboratorio.telefono);
          printf("Correo Electronico");
          gets(art[i].laboratorio.email);
     }
}

void ordenar (int n, struct articulo art[]){
     int i,j;
     struct articulo aux;
     for(i=0;i<n-1;i++){
          for(j=0;j<n-1;j++){
               if(art[j].clave>art[j+1].clave){
                    aux=art[j];
                    art[j]=art[j+1];
                    art[j+1]=aux;
               }
          }
     }
}

void cosultalista(int n, struct articulo art[]){
     int i;
     system("cls");
     puts("Consulta lista");
     for(i=0;i<n;i++){
          printf("Clave del producto: %d",art[i].clave);
          printf("Nombre del producto:");
          puts(art[i].nombreproducto);
          printf("Presentacion:");
          puts(art[i].presentacion);
          printf("Precio del articulo: $%10.2f",art[i].precioventa);
          (art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15);
          printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
          printf("Existencia del articulo: %d",art[i].existencia);
          printf("Nombre del laboratorio");
          puts(art[i].laboratorio.nombrelaboratorio);
          printf("Nombre de la calle");
          puts(art[i].laboratorio.calle);
          printf("Colonia");
          puts(art[i].laboratorio.colonia);
          printf("Cuidad");
          puts(art[i].laboratorio.ciudad);
          printf("Numero telefonico: %d",art[i].laboratorio.telefono);
          printf("Correo electronico");
          puts(art[i].laboratorio.email);
     }
}

void busqueda (int n, struct articulo art[]){
     int i;
     int posicion=-1;
     int b;
     system("cls");
     puts("Busqueda individual");
     printf("Clave del articulo a buscar");
     scanf("%d",&b);
     for(i=0;i<n;i++){
          if(b==art[i].clave){
               printf("Clave del producto: %d",art[i].clave);
               printf("Nombre del producto:");
               puts(art[i].nombreproducto);
               printf("Presentacion:");
               puts(art[i].presentacion);
               printf("Precio del articulo: $%10.2f",art[i].precioventa);
               art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15;
               printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
               printf("Existencia del articulo: %d",art[i].existencia);
               printf("Nombre del laboratorio");
               puts(art[i].laboratorio.nombrelaboratorio);
               printf("Nombre de la calle");
               puts(art[i].laboratorio.calle);
               printf("Colonia");
               puts(art[i].laboratorio.colonia);
               printf("Cuidad");
               puts(art[i].laboratorio.ciudad);
               printf("Numero telefonico: %d",art[i].laboratorio.telefono);
               printf("Correo electronico");
               puts(art[i].laboratorio.email);
          }
          else
               puts("Articulo no encontrado");
     }
}               
     
void modificarregistro (int n, struct articulo art[]){
     int i,op,b;
     printf("clave del producto que desea modificar");
     scanf("%d",&b);
     for(i=0;i<n;i++){
          if(b==art[i].clave){
               printf("Clave del producto: %d",art[i].clave);
               printf("Nombre del producto:");
               puts(art[i].nombreproducto);
               printf("Presentacion:");
               puts(art[i].presentacion);
               printf("Precio del articulo: $%10.2f",art[i].precioventa);
               art[i].preciodescuento=art[i].precioventa-art[i].precioventa*0.15;
               printf("Precio del articulo Con descuento: $%10.2f",art[i].preciodescuento);
               printf("Existencia del articulo: %d",art[i].existencia);
               printf("Nombre del laboratorio");
               puts(art[i].laboratorio.nombrelaboratorio);
               printf("Nombre de la calle");
               puts(art[i].laboratorio.calle);
               printf("Colonia");
               puts(art[i].laboratorio.colonia);
               printf("Cuidad");
               puts(art[i].laboratorio.ciudad);
               printf("Numero telefonico: %d",art[i].laboratorio.telefono);
               printf("Correo electronico");
               puts(art[i].laboratorio.email);
               do{
                    printf("¿Que desea modificar?");
                    printf("1.Clave del producto");
                    printf("2.Nombre del producto");
                    printf("3.Presentacion");
                    printf("4.Precio del articulo");
                    printf("5.Existencia del articulo");
                    printf("6.Nombre del laboratorio");
                    printf("7.Calle");
                    printf("8.Colonia");
                    printf("9.Cuidad");
                    printf("10.Numero telefonico");
                    printf("11.Correo electronico");
                    printf("12.Modificar todo");
                    printf("13.Salir");
                    scanf("%d",&op);
                    switch(op){
                         case(1):printf("Nueva clave");
                                 scanf("%d",&art[i].clave);
                                 break;
                         case(2):printf("Nuevo nombre del producto");
                                 gets(art[i].nombreproducto);
                                 break;
                         case(3):printf("Nueva presentacion");
                                 gets(art[i].presentacion);
                                 break;
                         case(4):printf("Nuevo precio de venta");
                                 scanf("%f",&art[i].precioventa);
                                 break;
                         case(5):printf("existencia");
                                 scanf("%d",&art[i].existencia);
                                 break;
                         case(6):printf("Nombre del laboratorio");
                                 gets(art[i].laboratorio.nombrelaboratorio);
                                 break;
                         case(7):("Calle");
                                 gets(art[i].laboratorio.calle);
                                 break;
                         case(8):printf("Colonia");
                                 gets(art[i].laboratorio.colonia);
                                 break;
                         case(9):printf("cuidad");
                                 gets(art[i].laboratorio.ciudad);
                                 break;
                         case(10):printf("Numero telefonico");
                                  scanf("%d",&art[i].laboratorio.telefono);
                                  break;
                         case(11):printf("Correo electronico");
                                  gets(art[i].laboratorio.email);
                                  break;
                         case(12):printf("Clave del producto");
                                  scanf("%d",&art[i].clave);
                                  printf("Nombre del producto");
                                  gets(art[i].nombreproducto);
                                  printf("presentacion");
                                  gets(art[i].presentacion);
                                  printf("Precio de venta");
                                  scanf("%f",&art[i].precioventa);
                                  printf("Existencia");
                                  scanf("%d",&art[i].existencia);
                                  printf("Nombre del laboratorio");
                                  gets(art[i].laboratorio.nombrelaboratorio);
                                  printf("Calle");
                                  gets(art[i].laboratorio.calle);
                                  printf("Colonia");
                                  gets(art[i].laboratorio.colonia);
                                  printf("Ciudad");
                                  gets(art[i].laboratorio.ciudad);
                                  printf("Numero Telefonico");
                                  scanf("%d",&art[i].laboratorio.telefono);
                                  printf("Correo Electronico");
                                  gets(art[i].laboratorio.email);
               }
               while(op>=12);
               }
               else
               printf("Articulo no encontrado");
               }
          
     
}   
}
void grabararchivo (int n ,struct articulo art[]){
     file *pa;
     char nombrearch[]="Farmacia.dat";
     int i;
     system("cls");
     if((pa=fopen(nombrearch,"wb"))==NULL){
          printf("No se pudo abrir el archivo");}
     for(i=0;i<n;i++){
          fwrite((art[],sizeof art[i],1,pa);
          }
     fclose(pa);
     printf("\n\n Archivo grabado con exito...");
     system("pause");
}

void leerarchivo (struct articulo art[]){
     file*pa;
     char nombrearch[]="Farmacia.dat";
     int i;
     system ("cls");
     if((pa=fopen(nombrearch"rb"))==NULL){
     	printf ("no se pudo abrir el archivo");}
     	i=0;
     	while (!feof(pa)){
     		fread(&art[i],zizeof art[i],1,pa );
     		i++;
     	}
     	fclose (pa);
     	printf("n\n\ archivo leido con exito ...");
     	system ("pause");
     	return 0 i-1;
     }

**Comment by AnabelBerumen** [comment]
me voy a dormir tengo un error y no se que es X_X

**Comment by kr1lo** [comment]
@AnabelBerumen  que es lo que te dice el error o en que momento se presenta el error?.
